NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('NewsPortal.urls')),
    # path('pages/', include('django.contrib.flatpages.urls')),
    path('accounts/', include('allauth.urls')),
]

NewsPaper/NewsPortal/models.py
from allauth.account.forms import SignupForm
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from django.db import models
from django.urls import reverse
from django import forms
from django.contrib.auth.models import User, Group
from django.core.cache import cache


article = 'STA'
news = 'NOV'

article_or_news = [
    (article, "Статья"),
    (news, "Новость")
]


class Author(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        default=1
    )
    author_rating = models.FloatField(default=0.0)

    def update_rating(self):
        all_posts = Post.objects.filter(post_author_id=self.user)
        post_rate = 0.0
        for post in all_posts:
            post_rate += post.post_rating * 3

        all_comments = Comment.objects.filter(comment_post_id=self.user)
        comment_rate = 0.0
        for comment in all_comments:
            comment_rate += comment.comment_rating

        self.author_rating = post_rate + comment_rate
        self.save()

    def __str__(self):
        return self.user.username


class Category(models.Model):
    subject = models.CharField(max_length=255, unique=True)
    subscribers = models.ManyToManyField(User, blank=True, related_name='categories')

    def __str__(self):
        return self.subject


class Post(models.Model):
    post_author = models.ForeignKey('Author', on_delete=models.CASCADE)
    article_news = models.CharField(max_length=3,
                                    choices=article_or_news,
                                    default=news)
    creation_time = models.DateTimeField(auto_now_add=True)
    post_category = models.ManyToManyField('Category', through='PostCategory')
    topic = models.CharField(max_length=255)
    text = models.TextField(default='Текст статьи/новости')
    post_rating = models.FloatField(default=0.0)

    def like(self):
        self.post_rating += 1.0
        self.save()
        return self.post_rating

    def dislike(self):
        self.post_rating -= 1.0
        self.save()
        return self.post_rating

    def preview(self):
        if len(self.text) <= 124:
            return self.text
        else:
            return self.text[:124] + '...'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        cache.delete(f'post-{self.pk}')


class PostCategory(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)


class Comment(models.Model):
    comment_post = models.ForeignKey('Post', on_delete=models.CASCADE)
    comment_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    comment_text = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)
    comment_rating = models.FloatField(default=0.0)

    def like(self):
        self.comment_rating += 1.0
        self.save()
        return self.comment_rating

    def dislike(self):
        self.comment_rating -= 1.0
        self.save()
        return self.comment_rating


class BaseRegisterForm(UserCreationForm):
    email = forms.EmailField(label="Email")
    first_name = forms.CharField(label="Имя")
    last_name = forms.CharField(label="Фамилия")

    class Meta:
        model = User
        fields = ("username",
                  "first_name",
                  "last_name",
                  "email",
                  "password1",
                  "password2",)

    def save(self, *args, **kwargs):
        user = super(BaseRegisterForm, self).save(*args, **kwargs)
        common_group = Group.objects.get(name='common')
        common_group.user_set.add(user)
        return user


class CommonSignupForm(SignupForm):

    def save(self, request):
        user = super(CommonSignupForm, self).save(request)
        common_group = Group.objects.get(name='common')
        common_group.user_set.add(user)
        return user

NewsPaper/templates/article_create_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Статья</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/templates/category_list.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Новости
{% endblock title %}

{% block content %}
{% if is_not_subscriber %}
<button style="margin: 10px"> <a href="{% url 'subscribe' category.id %}"> Подписаться на категорию {{ category }}</a> </button>
{% else %}
<button style="margin: 10px"> <a href="{% url 'unsubscribe' category.id %}"> Отписаться от категории {{ category }}</a> </button>
{% endif %}
    <h1>Все публикации в категории {{ category }}</h1>
    <hr>
    {% if category_news_list %}
        <table>
            <tr>
                <td>Заголовок</td>
                <td>Дата публикации</td>
                <td>Текст публикации</td>
                <td>Категории</td>
                <td>Тип</td>
            </tr>

            {% for post in category_news_list %}
            <tr>
                <td>{{ post.topic|censor }}</td>
                <td>{{ post.creation_time|date:'d M Y' }}</td>
                <td>{{ post.text|censor|truncatechars:21 }}</td>
                <td>
                {% for category in post.post_category.all %}
                    <a href="{% url 'category_list' category.id %}">{{ category }}</a>
                {% endfor %}
                </td>
                <td>{{ post.get_article_news_display }}</td>
            </tr>
        {% endfor %}
        </table>

    {% else %}
        <h2>Публикаций нет!</h2>
    {% endif %}

   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}

NewsPaper/templates/daily_news.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
<h2>Добрый день, {{ user.username }}! Новые статьи за неделю по <a href="{{ link }}">ссылке.</a>!</h2>
</body>
</html>

NewsPaper/templates/new_post_email.html
<!DOCTYPE html>

<html lang="ru">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Вышла новая статья</title>
</head>
<body>
<h2> Добрый день! {{ user.username }}! Новая <a href="{{ link }}">статья</a> в твоём любимом разделе!</h2>
<h3>{{ headline }}</h3>
<p>{{ article_text|truncatechars:50 }}</p>
</body>
</html>

NewsPaper/templates/post.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load cache %}

{% block title %}
Новость
{% endblock title %}

{% block content %}
{{ post.topic|censor }}
{{ post.creation_time|date:'d M Y' }}
{{ post.text|censor }}

<script>
document.getElementById('deleteId').href = windows.location.href;
</script>

{% cache 300 buttons %}

<h4>
    <a href="edit/" id="deleteId" class="button">Изменить</a>
</h4>

<h4>
    <a href="delete/" id="deleteId" class="button">Удалить</a>
</h4>

{% endcache %}

{% endblock content %}

NewsPaper/templates/post_create_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Новость</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/templates/posts.html
{% extends 'flatpages/default.html' %}
{% load crispy_forms_filters %}
{% load custom_filters %}
{% load custom_tags %}
{% load cache %}

{% block title %}
Новости
{% endblock title %}

{% block content %}

    <h1>Все новости</h1>

{% cache 60 buttons %}

<button> <a href="upgrade/"> Стать автором!</a> </button>

    <form action="" method="get">
        {{ filterset.form|crispy }}
        <input style="margin: 10px" type="submit" value="Найти" />

{% endcache %}

    </form>

    <h3>{{ page_obj.paginator.count }}</h3>
    <hr>
    {% if posts %}
        <table>
            <tr>
                <td>Заголовок</td>
                <td>Дата публикации</td>
                <td>Текст публикации</td>
                <td>Категории</td>
                <td>Тип</td>
            </tr>

            {% for post in posts %}
            <tr>
                <td>{{ post.topic|censor }}</td>
                <td>{{ post.creation_time|date:'d M Y' }}</td>
                <td>{{ post.text|censor|truncatechars:21 }}</td>
                <td>
                {% for category in post.post_category.all %}
                    <a href="{% url 'category_list' category.id %}">{{ category }}</a>
                {% endfor %}
                </td>
                <td>{{ post.get_article_news_display }}</td>
            </tr>
        {% endfor %}
        </table>

    {% else %}
        <h2>Публикаций нет!</h2>
    {% endif %}

   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}

NewsPaper/templates/profile.html
{% extends "flatpages/default.html" %}

{% block content %}
<h2>Страница авторизованного пользователя {{request.user.username}}</h2>
<div> Здесь может содержаться персональная информация для каждого пользователя </div>

<button> <a href='{% url "account_logout" %}'>Выйти</a> </button>

{% if is_not_author %}
<button> <a href='{% url "upgrade" %}'> Стать автором!</a> </button>
{% endif %}

{% endblock %}

NewsPaper/templates/subscribe.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h1 class="text-center">{{ message }} {{ category }}</h1>
{% endblock %}

NewsPaper/templates/unsubscribe.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h1 class="text-center">{{ message }} {{ category }}</h1>
{% endblock %}